package com.freesheep.biz.service;

import com.freesheep.biz.model.ActivityImgBO;

import java.util.List;

public interface ActivityImgService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_img
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_img
     *
     * @mbg.generated
     */
    int insert(ActivityImgBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_img
     *
     * @mbg.generated
     */
    int insertSelective(ActivityImgBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_img
     *
     * @mbg.generated
     */
    ActivityImgBO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_img
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ActivityImgBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_img
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActivityImgBO record);

    List<ActivityImgBO> getAllInfo();
}