package com.freesheep.biz.service;

import com.freesheep.biz.model.AppPageImgBO;

import java.util.List;

public interface AppPageImgService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_page_img
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_page_img
     *
     * @mbg.generated
     */
    int insert(AppPageImgBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_page_img
     *
     * @mbg.generated
     */
    int insertSelective(AppPageImgBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_page_img
     *
     * @mbg.generated
     */
    AppPageImgBO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_page_img
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AppPageImgBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_page_img
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(AppPageImgBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_page_img
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AppPageImgBO record);

    List<AppPageImgBO> getAllInfo();

}