package com.freesheep.biz.service;

import com.freesheep.biz.model.DeviceTestInfoBO;

public interface DeviceTestInfoService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_test_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_test_info
     *
     * @mbg.generated
     */
    int insert(DeviceTestInfoBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_test_info
     *
     * @mbg.generated
     */
    int insertSelective(DeviceTestInfoBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_test_info
     *
     * @mbg.generated
     */
    DeviceTestInfoBO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_test_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DeviceTestInfoBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_test_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DeviceTestInfoBO record);
}