package com.freesheep.biz.service;

import com.freesheep.biz.model.FictitiousDeviceInfoBO;

import java.util.List;

public interface FictitiousDeviceInfoService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fictitious_device_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fictitious_device_info
     *
     * @mbg.generated
     */
    int insert(FictitiousDeviceInfoBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fictitious_device_info
     *
     * @mbg.generated
     */
    int insertSelective(FictitiousDeviceInfoBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fictitious_device_info
     *
     * @mbg.generated
     */
    FictitiousDeviceInfoBO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fictitious_device_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FictitiousDeviceInfoBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fictitious_device_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FictitiousDeviceInfoBO record);
    List<FictitiousDeviceInfoBO> getHistoryInfo(long deviceId, String startTime, String endTime);
    long getCountForTime(long deviceId, String start, String end);
}