package com.freesheep.biz.service;

import com.freesheep.biz.model.FoodInfoBO;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

public interface FoodInfoService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_info
     *
     * @mbg.generated
     */
    int insert(FoodInfoBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_info
     *
     * @mbg.generated
     */
    int insertSelective(FoodInfoBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_info
     *
     * @mbg.generated
     */
    FoodInfoBO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FoodInfoBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(FoodInfoBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FoodInfoBO record);

    Page<FoodInfoBO> getFoodInfoList(Pageable pageable);
}