package com.freesheep.biz.service;

import com.freesheep.biz.model.IntoWarehouseOrderBO;

public interface IntoWarehouseOrderService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table into_warehouse_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table into_warehouse_order
     *
     * @mbg.generated
     */
    int insert(IntoWarehouseOrderBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table into_warehouse_order
     *
     * @mbg.generated
     */
    long insertSelective(IntoWarehouseOrderBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table into_warehouse_order
     *
     * @mbg.generated
     */
    IntoWarehouseOrderBO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table into_warehouse_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IntoWarehouseOrderBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table into_warehouse_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IntoWarehouseOrderBO record);
    IntoWarehouseOrderBO selectIntoWarehouseOrderByNum(String systemNum);
}