package com.freesheep.biz.service;

import com.freesheep.biz.model.LogisticsInfoBO;

public interface LogisticsInfoService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_info
     *
     * @mbg.generated
     */
    int insert(LogisticsInfoBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_info
     *
     * @mbg.generated
     */
    int insertSelective(LogisticsInfoBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_info
     *
     * @mbg.generated
     */
    LogisticsInfoBO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LogisticsInfoBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LogisticsInfoBO record);

    LogisticsInfoBO selectInfoByDeliveryOrderId(String deliveryOrderId);

}