package com.freesheep.biz.service;

import com.freesheep.biz.model.OrderCancelBO;

public interface OrderCancelService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cancel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cancel
     *
     * @mbg.generated
     */
    int insert(OrderCancelBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cancel
     *
     * @mbg.generated
     */
    int insertSelective(OrderCancelBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cancel
     *
     * @mbg.generated
     */
    OrderCancelBO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cancel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderCancelBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cancel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderCancelBO record);
}