package com.freesheep.biz.service;

import com.freesheep.biz.model.OutgoingProductInfoBO;

public interface OutgoingProductInfoService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outgoing_product_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outgoing_product_info
     *
     * @mbg.generated
     */
    int insert(OutgoingProductInfoBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outgoing_product_info
     *
     * @mbg.generated
     */
    int insertSelective(OutgoingProductInfoBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outgoing_product_info
     *
     * @mbg.generated
     */
    OutgoingProductInfoBO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outgoing_product_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OutgoingProductInfoBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outgoing_product_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OutgoingProductInfoBO record);

    OutgoingProductInfoBO selectInfoByOrder(String orderNum, String goodsCode);
}