package com.freesheep.biz.service;

import com.freesheep.biz.model.PermissionGroupBO;

public interface PermissionGroupService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_group
     *
     * @mbg.generated
     */
    int insert(PermissionGroupBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_group
     *
     * @mbg.generated
     */
    int insertSelective(PermissionGroupBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_group
     *
     * @mbg.generated
     */
    PermissionGroupBO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PermissionGroupBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PermissionGroupBO record);
}