package com.freesheep.biz.service;

import com.freesheep.biz.model.ProductCouponBO;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import java.util.List;

public interface ProductCouponService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_coupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_coupon
     *
     * @mbg.generated
     */
    int insert(ProductCouponBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_coupon
     *
     * @mbg.generated
     */
    int insertSelective(ProductCouponBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_coupon
     *
     * @mbg.generated
     */
    ProductCouponBO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductCouponBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductCouponBO record);
    Page<ProductCouponBO> getCouponList(Pageable pageable, long uid);
    ProductCouponBO getInfoByCode(String couponCode);
    boolean insertCouponList(List<ProductCouponBO> couponList);
}