package com.freesheep.biz.service;

import com.freesheep.biz.model.ProductShareBO;

public interface ProductShareService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_share
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_share
     *
     * @mbg.generated
     */
    int insert(ProductShareBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_share
     *
     * @mbg.generated
     */
    int insertSelective(ProductShareBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_share
     *
     * @mbg.generated
     */
    ProductShareBO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_share
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductShareBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_share
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductShareBO record);

    ProductShareBO selectProductShare(long uid, long pid);
}