package com.freesheep.biz.service;

import com.freesheep.biz.model.ReturnOrderInfoBO;

public interface ReturnOrderInfoService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_order_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_order_info
     *
     * @mbg.generated
     */
    int insert(ReturnOrderInfoBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_order_info
     *
     * @mbg.generated
     */
    int insertSelective(ReturnOrderInfoBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_order_info
     *
     * @mbg.generated
     */
    ReturnOrderInfoBO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_order_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReturnOrderInfoBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_order_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReturnOrderInfoBO record);

    ReturnOrderInfoBO selectReturnOrderByNum(String orderNum, String systemOrderNum, String goodsCode);

}