package com.freesheep.biz.service;

import com.freesheep.biz.model.StCartBO;

public interface StCartService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_cart
     *
     * @mbg.generated
     */
    int insert(StCartBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_cart
     *
     * @mbg.generated
     */
    int insertSelective(StCartBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_cart
     *
     * @mbg.generated
     */
    StCartBO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StCartBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StCartBO record);
}