package com.freesheep.biz.service;

import com.freesheep.biz.model.StClaimOrderBO;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

public interface StClaimOrderService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_claim_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_claim_order
     *
     * @mbg.generated
     */
    int insert(StClaimOrderBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_claim_order
     *
     * @mbg.generated
     */
    long insertSelective(StClaimOrderBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_claim_order
     *
     * @mbg.generated
     */
    StClaimOrderBO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_claim_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StClaimOrderBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_claim_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(StClaimOrderBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_claim_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StClaimOrderBO record);

    Page<StClaimOrderBO> selectOrderListByUid(Pageable pageable, long uid, int type);

    StClaimOrderBO selectOrderDetail(long oid);
    StClaimOrderBO selectByOrderNum(String orderNum);

}