package com.freesheep.biz.service;

import com.freesheep.biz.model.StDeviceStatusBO;

public interface StDeviceStatusService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_device_status
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_device_status
     *
     * @mbg.generated
     */
    int insert(StDeviceStatusBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_device_status
     *
     * @mbg.generated
     */
    int insertSelective(StDeviceStatusBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_device_status
     *
     * @mbg.generated
     */
    StDeviceStatusBO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_device_status
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StDeviceStatusBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_device_status
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StDeviceStatusBO record);
}