package com.freesheep.biz.service;

import com.freesheep.biz.model.StDeviceTypeBO;

public interface StDeviceTypeService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_device_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_device_type
     *
     * @mbg.generated
     */
    int insert(StDeviceTypeBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_device_type
     *
     * @mbg.generated
     */
    int insertSelective(StDeviceTypeBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_device_type
     *
     * @mbg.generated
     */
    StDeviceTypeBO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_device_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StDeviceTypeBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_device_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StDeviceTypeBO record);
}