package com.freesheep.biz.service;

import com.freesheep.biz.model.StFavoriteBO;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

public interface StFavoriteService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_favorite
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_favorite
     *
     * @mbg.generated
     */
    int insert(StFavoriteBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_favorite
     *
     * @mbg.generated
     */
    int insertSelective(StFavoriteBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_favorite
     *
     * @mbg.generated
     */
    StFavoriteBO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_favorite
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StFavoriteBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_favorite
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StFavoriteBO record);

    Page<StFavoriteBO> selectCollectionList(Pageable pageable, long uid);
    long selectCollectionCount(int uid, int pid);
}