package com.freesheep.biz.service;

import com.freesheep.biz.model.StMomentsBO;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import java.util.List;

public interface StMomentsService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_moments
     *
     * @mbg.generated
     */
    StMomentsBO selectByPrimaryKey(Integer id);


    boolean updateShareCount(StMomentsBO momentsBO);
    boolean updateCommentCount(StMomentsBO momentsBO);

    List<StMomentsBO> selectMomentList(int mid);
    Page<StMomentsBO> selectMomentIdList(Pageable pageable);
    Page<StMomentsBO> selectMomentIdListById(Pageable pageable, int uid);
    int insertMoment(StMomentsBO momentsBO);
    List<StMomentsBO> selectMediaList(List<Integer> mediaIdList);
    List<StMomentsBO> selectMomentsDigList(List<Integer> mediaIdList);
    List<StMomentsBO> selectMomentsDisList(List<Integer> mediaIdList);
}