package com.freesheep.biz.service;

import com.freesheep.biz.model.StMomentsDigsBO;

public interface StMomentsDigsService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_moments_digs
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_moments_digs
     *
     * @mbg.generated
     */
    int insert(StMomentsDigsBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_moments_digs
     *
     * @mbg.generated
     */
    int insertSelective(StMomentsDigsBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_moments_digs
     *
     * @mbg.generated
     */
    StMomentsDigsBO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_moments_digs
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StMomentsDigsBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_moments_digs
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StMomentsDigsBO record);
}