package com.freesheep.biz.service;

import com.freesheep.biz.model.StOrderAddressesBO;

public interface StOrderAddressesService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_order_addresses
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_order_addresses
     *
     * @mbg.generated
     */
    int insert(StOrderAddressesBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_order_addresses
     *
     * @mbg.generated
     */
    int insertSelective(StOrderAddressesBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_order_addresses
     *
     * @mbg.generated
     */
    StOrderAddressesBO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_order_addresses
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StOrderAddressesBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_order_addresses
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StOrderAddressesBO record);



}