package com.freesheep.biz.service;

import com.freesheep.biz.model.StProductsBO;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;

import java.util.List;

public interface StProductsService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_products
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_products
     *
     * @mbg.generated
     */
    int insert(StProductsBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_products
     *
     * @mbg.generated
     */
    long insertSelective(StProductsBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_products
     *
     * @mbg.generated
     */
    StProductsBO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_products
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StProductsBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_products
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(StProductsBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_products
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StProductsBO record);

    List<StProductsBO> getProductList();

    Page<StProductsBO> getAllList(PageRequest pageRequest);
    StProductsBO getProductInfoById(long id);

}