package com.freesheep.biz.service;

import com.freesheep.biz.model.StSheepBO;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

public interface StSheepService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_sheep
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_sheep
     *
     * @mbg.generated
     */
    int insert(StSheepBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_sheep
     *
     * @mbg.generated
     */
    int insertSelective(StSheepBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_sheep
     *
     * @mbg.generated
     */
    StSheepBO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_sheep
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StSheepBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_sheep
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StSheepBO record);

    long sheepCountByUid(long userId);
    Page<StSheepBO> selectSheepList(Pageable pageable);
    Page<StSheepBO> selectSheepUserList(Pageable pageable, int userId);
    StSheepBO selectUserSheepInfo(long userId, long sheepId);
    int lockSheepById(long id, long uid);
    int unLockSheepById(long id);
}