package com.freesheep.biz.service;

import com.freesheep.biz.model.SyncProductBO;

public interface SyncProductService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sync_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sync_product
     *
     * @mbg.generated
     */
    int insert(SyncProductBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sync_product
     *
     * @mbg.generated
     */
    int insertSelective(SyncProductBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sync_product
     *
     * @mbg.generated
     */
    SyncProductBO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sync_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SyncProductBO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sync_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SyncProductBO record);
}