package com.freesheep.biz.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.Date;

public class AdminUserBO {

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.permission_group_id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer permissionGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.user_name
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.login_name
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.login_pwd
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonIgnore
    private String loginPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.claim_order
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer claimOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.goods_order
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer goodsOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.device_list
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer deviceList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.device_type
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer deviceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.device_status
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer deviceStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.pasture_list
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer pastureList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.sheep_breeds_list
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer sheepBreedsList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.is_super_admin
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer isSuperAdmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.create_time
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.modify_time
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.id
     *
     * @return the value of admin_user.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.id
     *
     * @param id the value for admin_user.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.permission_group_id
     *
     * @return the value of admin_user.permission_group_id
     *
     * @mbg.generated
     */
    public Integer getPermissionGroupId() {
        return permissionGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.permission_group_id
     *
     * @param permissionGroupId the value for admin_user.permission_group_id
     *
     * @mbg.generated
     */
    public void setPermissionGroupId(Integer permissionGroupId) {
        this.permissionGroupId = permissionGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.user_name
     *
     * @return the value of admin_user.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.user_name
     *
     * @param userName the value for admin_user.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.login_name
     *
     * @return the value of admin_user.login_name
     *
     * @mbg.generated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.login_name
     *
     * @param loginName the value for admin_user.login_name
     *
     * @mbg.generated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.login_pwd
     *
     * @return the value of admin_user.login_pwd
     *
     * @mbg.generated
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.login_pwd
     *
     * @param loginPwd the value for admin_user.login_pwd
     *
     * @mbg.generated
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd == null ? null : loginPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.claim_order
     *
     * @return the value of admin_user.claim_order
     *
     * @mbg.generated
     */
    public Integer getClaimOrder() {
        return claimOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.claim_order
     *
     * @param claimOrder the value for admin_user.claim_order
     *
     * @mbg.generated
     */
    public void setClaimOrder(Integer claimOrder) {
        this.claimOrder = claimOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.goods_order
     *
     * @return the value of admin_user.goods_order
     *
     * @mbg.generated
     */
    public Integer getGoodsOrder() {
        return goodsOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.goods_order
     *
     * @param goodsOrder the value for admin_user.goods_order
     *
     * @mbg.generated
     */
    public void setGoodsOrder(Integer goodsOrder) {
        this.goodsOrder = goodsOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.device_list
     *
     * @return the value of admin_user.device_list
     *
     * @mbg.generated
     */
    public Integer getDeviceList() {
        return deviceList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.device_list
     *
     * @param deviceList the value for admin_user.device_list
     *
     * @mbg.generated
     */
    public void setDeviceList(Integer deviceList) {
        this.deviceList = deviceList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.device_type
     *
     * @return the value of admin_user.device_type
     *
     * @mbg.generated
     */
    public Integer getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.device_type
     *
     * @param deviceType the value for admin_user.device_type
     *
     * @mbg.generated
     */
    public void setDeviceType(Integer deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.device_status
     *
     * @return the value of admin_user.device_status
     *
     * @mbg.generated
     */
    public Integer getDeviceStatus() {
        return deviceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.device_status
     *
     * @param deviceStatus the value for admin_user.device_status
     *
     * @mbg.generated
     */
    public void setDeviceStatus(Integer deviceStatus) {
        this.deviceStatus = deviceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.pasture_list
     *
     * @return the value of admin_user.pasture_list
     *
     * @mbg.generated
     */
    public Integer getPastureList() {
        return pastureList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.pasture_list
     *
     * @param pastureList the value for admin_user.pasture_list
     *
     * @mbg.generated
     */
    public void setPastureList(Integer pastureList) {
        this.pastureList = pastureList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.sheep_breeds_list
     *
     * @return the value of admin_user.sheep_breeds_list
     *
     * @mbg.generated
     */
    public Integer getSheepBreedsList() {
        return sheepBreedsList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.sheep_breeds_list
     *
     * @param sheepBreedsList the value for admin_user.sheep_breeds_list
     *
     * @mbg.generated
     */
    public void setSheepBreedsList(Integer sheepBreedsList) {
        this.sheepBreedsList = sheepBreedsList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.is_super_admin
     *
     * @return the value of admin_user.is_super_admin
     *
     * @mbg.generated
     */
    public Integer getIsSuperAdmin() {
        return isSuperAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.is_super_admin
     *
     * @param isSuperAdmin the value for admin_user.is_super_admin
     *
     * @mbg.generated
     */
    public void setIsSuperAdmin(Integer isSuperAdmin) {
        this.isSuperAdmin = isSuperAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.create_time
     *
     * @return the value of admin_user.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.create_time
     *
     * @param createTime the value for admin_user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.modify_time
     *
     * @return the value of admin_user.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.modify_time
     *
     * @param modifyTime the value for admin_user.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
}