package com.freesheep.biz.model;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.Date;

public class AppPageImgBO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_page_img.id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_page_img.url
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_page_img.page_type
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer pageType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_page_img.create_time
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_page_img.modify_time
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_page_img.remark
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_page_img.id
     *
     * @return the value of app_page_img.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_page_img.id
     *
     * @param id the value for app_page_img.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_page_img.url
     *
     * @return the value of app_page_img.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_page_img.url
     *
     * @param url the value for app_page_img.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_page_img.page_type
     *
     * @return the value of app_page_img.page_type
     *
     * @mbg.generated
     */
    public Integer getPageType() {
        return pageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_page_img.page_type
     *
     * @param pageType the value for app_page_img.page_type
     *
     * @mbg.generated
     */
    public void setPageType(Integer pageType) {
        this.pageType = pageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_page_img.create_time
     *
     * @return the value of app_page_img.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_page_img.create_time
     *
     * @param createTime the value for app_page_img.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_page_img.modify_time
     *
     * @return the value of app_page_img.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_page_img.modify_time
     *
     * @param modifyTime the value for app_page_img.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_page_img.remark
     *
     * @return the value of app_page_img.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_page_img.remark
     *
     * @param remark the value for app_page_img.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}