package com.freesheep.biz.model;

public class DeviceTestInfoBO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_test_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_test_info.device_num
     *
     * @mbg.generated
     */
    private String deviceNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_test_info.device_date
     *
     * @mbg.generated
     */
    private String deviceDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_test_info.device_time
     *
     * @mbg.generated
     */
    private String deviceTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_test_info.longitude
     *
     * @mbg.generated
     */
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_test_info.latitude
     *
     * @mbg.generated
     */
    private String latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_test_info.is_location
     *
     * @mbg.generated
     */
    private String isLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_test_info.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_test_info.modify_time
     *
     * @mbg.generated
     */
    private String modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_test_info.id
     *
     * @return the value of device_test_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_test_info.id
     *
     * @param id the value for device_test_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_test_info.device_num
     *
     * @return the value of device_test_info.device_num
     *
     * @mbg.generated
     */
    public String getDeviceNum() {
        return deviceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_test_info.device_num
     *
     * @param deviceNum the value for device_test_info.device_num
     *
     * @mbg.generated
     */
    public void setDeviceNum(String deviceNum) {
        this.deviceNum = deviceNum == null ? null : deviceNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_test_info.device_date
     *
     * @return the value of device_test_info.device_date
     *
     * @mbg.generated
     */
    public String getDeviceDate() {
        return deviceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_test_info.device_date
     *
     * @param deviceDate the value for device_test_info.device_date
     *
     * @mbg.generated
     */
    public void setDeviceDate(String deviceDate) {
        this.deviceDate = deviceDate == null ? null : deviceDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_test_info.device_time
     *
     * @return the value of device_test_info.device_time
     *
     * @mbg.generated
     */
    public String getDeviceTime() {
        return deviceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_test_info.device_time
     *
     * @param deviceTime the value for device_test_info.device_time
     *
     * @mbg.generated
     */
    public void setDeviceTime(String deviceTime) {
        this.deviceTime = deviceTime == null ? null : deviceTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_test_info.longitude
     *
     * @return the value of device_test_info.longitude
     *
     * @mbg.generated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_test_info.longitude
     *
     * @param longitude the value for device_test_info.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_test_info.latitude
     *
     * @return the value of device_test_info.latitude
     *
     * @mbg.generated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_test_info.latitude
     *
     * @param latitude the value for device_test_info.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_test_info.is_location
     *
     * @return the value of device_test_info.is_location
     *
     * @mbg.generated
     */
    public String getIsLocation() {
        return isLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_test_info.is_location
     *
     * @param isLocation the value for device_test_info.is_location
     *
     * @mbg.generated
     */
    public void setIsLocation(String isLocation) {
        this.isLocation = isLocation == null ? null : isLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_test_info.create_time
     *
     * @return the value of device_test_info.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_test_info.create_time
     *
     * @param createTime the value for device_test_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_test_info.modify_time
     *
     * @return the value of device_test_info.modify_time
     *
     * @mbg.generated
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_test_info.modify_time
     *
     * @param modifyTime the value for device_test_info.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime == null ? null : modifyTime.trim();
    }
}