package com.freesheep.biz.model;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.Date;

public class FictitiousSheepBO {


    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String deviceLongitude;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String deviceLatitude;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer accuracy;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private long step;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fictitious_sheep.id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fictitious_sheep.device_id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Long deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fictitious_sheep.user_id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fictitious_sheep.sheep_nickname
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String sheepNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fictitious_sheep.gender
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fictitious_sheep.sheep_img
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String sheepImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fictitious_sheep.sheep_status
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer sheepStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fictitious_sheep.operate_uid
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Long operateUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fictitious_sheep.birth_day
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Date birthDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fictitious_sheep.claim_time
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Date claimTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fictitious_sheep.pasture_id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Long pastureId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fictitious_sheep.sheep_breeds_id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Long sheepBreedsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fictitious_sheep.create_time
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fictitious_sheep.modify_time
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fictitious_sheep.id
     *
     * @return the value of fictitious_sheep.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fictitious_sheep.id
     *
     * @param id the value for fictitious_sheep.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fictitious_sheep.device_id
     *
     * @return the value of fictitious_sheep.device_id
     *
     * @mbg.generated
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fictitious_sheep.device_id
     *
     * @param deviceId the value for fictitious_sheep.device_id
     *
     * @mbg.generated
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fictitious_sheep.user_id
     *
     * @return the value of fictitious_sheep.user_id
     *
     * @mbg.generated
     */
    public long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fictitious_sheep.user_id
     *
     * @param userId the value for fictitious_sheep.user_id
     *
     * @mbg.generated
     */
    public void setUserId(long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fictitious_sheep.sheep_nickname
     *
     * @return the value of fictitious_sheep.sheep_nickname
     *
     * @mbg.generated
     */
    public String getSheepNickname() {
        return sheepNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fictitious_sheep.sheep_nickname
     *
     * @param sheepNickname the value for fictitious_sheep.sheep_nickname
     *
     * @mbg.generated
     */
    public void setSheepNickname(String sheepNickname) {
        this.sheepNickname = sheepNickname == null ? null : sheepNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fictitious_sheep.gender
     *
     * @return the value of fictitious_sheep.gender
     *
     * @mbg.generated
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fictitious_sheep.gender
     *
     * @param gender the value for fictitious_sheep.gender
     *
     * @mbg.generated
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fictitious_sheep.sheep_img
     *
     * @return the value of fictitious_sheep.sheep_img
     *
     * @mbg.generated
     */
    public String getSheepImg() {
        return sheepImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fictitious_sheep.sheep_img
     *
     * @param sheepImg the value for fictitious_sheep.sheep_img
     *
     * @mbg.generated
     */
    public void setSheepImg(String sheepImg) {
        this.sheepImg = sheepImg == null ? null : sheepImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fictitious_sheep.sheep_status
     *
     * @return the value of fictitious_sheep.sheep_status
     *
     * @mbg.generated
     */
    public Integer getSheepStatus() {
        return sheepStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fictitious_sheep.sheep_status
     *
     * @param sheepStatus the value for fictitious_sheep.sheep_status
     *
     * @mbg.generated
     */
    public void setSheepStatus(Integer sheepStatus) {
        this.sheepStatus = sheepStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fictitious_sheep.operate_uid
     *
     * @return the value of fictitious_sheep.operate_uid
     *
     * @mbg.generated
     */
    public Long getOperateUid() {
        return operateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fictitious_sheep.operate_uid
     *
     * @param operateUid the value for fictitious_sheep.operate_uid
     *
     * @mbg.generated
     */
    public void setOperateUid(Long operateUid) {
        this.operateUid = operateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fictitious_sheep.birth_day
     *
     * @return the value of fictitious_sheep.birth_day
     *
     * @mbg.generated
     */
    public Date getBirthDay() {
        return birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fictitious_sheep.birth_day
     *
     * @param birthDay the value for fictitious_sheep.birth_day
     *
     * @mbg.generated
     */
    public void setBirthDay(Date birthDay) {
        this.birthDay = birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fictitious_sheep.claim_time
     *
     * @return the value of fictitious_sheep.claim_time
     *
     * @mbg.generated
     */
    public Date getClaimTime() {
        return claimTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fictitious_sheep.claim_time
     *
     * @param claimTime the value for fictitious_sheep.claim_time
     *
     * @mbg.generated
     */
    public void setClaimTime(Date claimTime) {
        this.claimTime = claimTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fictitious_sheep.pasture_id
     *
     * @return the value of fictitious_sheep.pasture_id
     *
     * @mbg.generated
     */
    public Long getPastureId() {
        return pastureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fictitious_sheep.pasture_id
     *
     * @param pastureId the value for fictitious_sheep.pasture_id
     *
     * @mbg.generated
     */
    public void setPastureId(Long pastureId) {
        this.pastureId = pastureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fictitious_sheep.sheep_breeds_id
     *
     * @return the value of fictitious_sheep.sheep_breeds_id
     *
     * @mbg.generated
     */
    public Long getSheepBreedsId() {
        return sheepBreedsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fictitious_sheep.sheep_breeds_id
     *
     * @param sheepBreedsId the value for fictitious_sheep.sheep_breeds_id
     *
     * @mbg.generated
     */
    public void setSheepBreedsId(Long sheepBreedsId) {
        this.sheepBreedsId = sheepBreedsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fictitious_sheep.create_time
     *
     * @return the value of fictitious_sheep.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fictitious_sheep.create_time
     *
     * @param createTime the value for fictitious_sheep.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fictitious_sheep.modify_time
     *
     * @return the value of fictitious_sheep.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fictitious_sheep.modify_time
     *
     * @param modifyTime the value for fictitious_sheep.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public String getDeviceLongitude() {
        return deviceLongitude;
    }

    public void setDeviceLongitude(String deviceLongitude) {
        this.deviceLongitude = deviceLongitude;
    }

    public String getDeviceLatitude() {
        return deviceLatitude;
    }

    public void setDeviceLatitude(String deviceLatitude) {
        this.deviceLatitude = deviceLatitude;
    }

    public Integer getAccuracy() {
        return accuracy;
    }

    public void setAccuracy(Integer accuracy) {
        this.accuracy = accuracy;
    }

    public long getStep() {
        return step;
    }

    public void setStep(long step) {
        this.step = step;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
}