package com.freesheep.biz.model;

import java.util.Date;

public class FictitiousDeviceBO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fictitious_device.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fictitious_device.device_num
     *
     * @mbg.generated
     */
    private String deviceNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fictitious_device.device_type_id
     *
     * @mbg.generated
     */
    private Integer deviceTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fictitious_device.device_power
     *
     * @mbg.generated
     */
    private Integer devicePower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fictitious_device.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fictitious_device.ip_address
     *
     * @mbg.generated
     */
    private String ipAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fictitious_device.device_status_id
     *
     * @mbg.generated
     */
    private Long deviceStatusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fictitious_device.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fictitious_device.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fictitious_device.id
     *
     * @return the value of fictitious_device.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fictitious_device.id
     *
     * @param id the value for fictitious_device.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fictitious_device.device_num
     *
     * @return the value of fictitious_device.device_num
     *
     * @mbg.generated
     */
    public String getDeviceNum() {
        return deviceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fictitious_device.device_num
     *
     * @param deviceNum the value for fictitious_device.device_num
     *
     * @mbg.generated
     */
    public void setDeviceNum(String deviceNum) {
        this.deviceNum = deviceNum == null ? null : deviceNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fictitious_device.device_type_id
     *
     * @return the value of fictitious_device.device_type_id
     *
     * @mbg.generated
     */
    public Integer getDeviceTypeId() {
        return deviceTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fictitious_device.device_type_id
     *
     * @param deviceTypeId the value for fictitious_device.device_type_id
     *
     * @mbg.generated
     */
    public void setDeviceTypeId(Integer deviceTypeId) {
        this.deviceTypeId = deviceTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fictitious_device.device_power
     *
     * @return the value of fictitious_device.device_power
     *
     * @mbg.generated
     */
    public Integer getDevicePower() {
        return devicePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fictitious_device.device_power
     *
     * @param devicePower the value for fictitious_device.device_power
     *
     * @mbg.generated
     */
    public void setDevicePower(Integer devicePower) {
        this.devicePower = devicePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fictitious_device.phone
     *
     * @return the value of fictitious_device.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fictitious_device.phone
     *
     * @param phone the value for fictitious_device.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fictitious_device.ip_address
     *
     * @return the value of fictitious_device.ip_address
     *
     * @mbg.generated
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fictitious_device.ip_address
     *
     * @param ipAddress the value for fictitious_device.ip_address
     *
     * @mbg.generated
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress == null ? null : ipAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fictitious_device.device_status_id
     *
     * @return the value of fictitious_device.device_status_id
     *
     * @mbg.generated
     */
    public Long getDeviceStatusId() {
        return deviceStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fictitious_device.device_status_id
     *
     * @param deviceStatusId the value for fictitious_device.device_status_id
     *
     * @mbg.generated
     */
    public void setDeviceStatusId(Long deviceStatusId) {
        this.deviceStatusId = deviceStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fictitious_device.create_time
     *
     * @return the value of fictitious_device.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fictitious_device.create_time
     *
     * @param createTime the value for fictitious_device.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fictitious_device.modify_time
     *
     * @return the value of fictitious_device.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fictitious_device.modify_time
     *
     * @param modifyTime the value for fictitious_device.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}