package com.freesheep.biz.model;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.Date;

public class FoodInfoBO {

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String nickname;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String avator;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer gender;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer isShow;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_info.id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_info.user_id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_info.first_img
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String firstImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_info.description
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_info.title
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_info.create_time
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_info.modify_time
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_info.content
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_info.id
     *
     * @return the value of food_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_info.id
     *
     * @param id the value for food_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_info.user_id
     *
     * @return the value of food_info.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_info.user_id
     *
     * @param userId the value for food_info.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_info.first_img
     *
     * @return the value of food_info.first_img
     *
     * @mbg.generated
     */
    public String getFirstImg() {
        return firstImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_info.first_img
     *
     * @param firstImg the value for food_info.first_img
     *
     * @mbg.generated
     */
    public void setFirstImg(String firstImg) {
        this.firstImg = firstImg == null ? null : firstImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_info.description
     *
     * @return the value of food_info.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_info.description
     *
     * @param description the value for food_info.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_info.title
     *
     * @return the value of food_info.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_info.title
     *
     * @param title the value for food_info.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_info.create_time
     *
     * @return the value of food_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_info.create_time
     *
     * @param createTime the value for food_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_info.modify_time
     *
     * @return the value of food_info.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_info.modify_time
     *
     * @param modifyTime the value for food_info.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_info.content
     *
     * @return the value of food_info.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_info.content
     *
     * @param content the value for food_info.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getAvator() {
        return avator;
    }

    public void setAvator(String avator) {
        this.avator = avator;
    }

    public Integer getGender() {
        return gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public Integer getIsShow() {
        return isShow;
    }

    public void setIsShow(Integer isShow) {
        this.isShow = isShow;
    }
}