package com.freesheep.biz.model;

import java.util.Date;

public class IntoWarehouseOrderBO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.order_num
     *
     * @mbg.generated
     */
    private String orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.purchase_order_code
     *
     * @mbg.generated
     */
    private String purchaseOrderCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.warehouse_code
     *
     * @mbg.generated
     */
    private String warehouseCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.system_order_num
     *
     * @mbg.generated
     */
    private String systemOrderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.order_type
     *
     * @mbg.generated
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.order_status
     *
     * @mbg.generated
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.logistics_code
     *
     * @mbg.generated
     */
    private String logisticsCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.logistics_name
     *
     * @mbg.generated
     */
    private String logisticsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.express_code
     *
     * @mbg.generated
     */
    private String expressCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.send_company
     *
     * @mbg.generated
     */
    private String sendCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.send_name
     *
     * @mbg.generated
     */
    private String sendName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.send_tel
     *
     * @mbg.generated
     */
    private String sendTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.send_mobile
     *
     * @mbg.generated
     */
    private String sendMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.send_email
     *
     * @mbg.generated
     */
    private String sendEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.send_province
     *
     * @mbg.generated
     */
    private String sendProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.send_city
     *
     * @mbg.generated
     */
    private String sendCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.send_area
     *
     * @mbg.generated
     */
    private String sendArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.send_detail_address
     *
     * @mbg.generated
     */
    private String sendDetailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.receiver_company
     *
     * @mbg.generated
     */
    private String receiverCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.receiver_name
     *
     * @mbg.generated
     */
    private String receiverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.receiver_tel
     *
     * @mbg.generated
     */
    private String receiverTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.receiver_mobile
     *
     * @mbg.generated
     */
    private String receiverMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.receiver_email
     *
     * @mbg.generated
     */
    private String receiverEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.receiver_province
     *
     * @mbg.generated
     */
    private String receiverProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.receiver_city
     *
     * @mbg.generated
     */
    private String receiverCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.receiver_area
     *
     * @mbg.generated
     */
    private String receiverArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.receiver_detail_address
     *
     * @mbg.generated
     */
    private String receiverDetailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.system_remark
     *
     * @mbg.generated
     */
    private String systemRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.expect_start_time
     *
     * @mbg.generated
     */
    private Date expectStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.expect_end_time
     *
     * @mbg.generated
     */
    private Date expectEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column into_warehouse_order.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.id
     *
     * @return the value of into_warehouse_order.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.id
     *
     * @param id the value for into_warehouse_order.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.order_num
     *
     * @return the value of into_warehouse_order.order_num
     *
     * @mbg.generated
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.order_num
     *
     * @param orderNum the value for into_warehouse_order.order_num
     *
     * @mbg.generated
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.purchase_order_code
     *
     * @return the value of into_warehouse_order.purchase_order_code
     *
     * @mbg.generated
     */
    public String getPurchaseOrderCode() {
        return purchaseOrderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.purchase_order_code
     *
     * @param purchaseOrderCode the value for into_warehouse_order.purchase_order_code
     *
     * @mbg.generated
     */
    public void setPurchaseOrderCode(String purchaseOrderCode) {
        this.purchaseOrderCode = purchaseOrderCode == null ? null : purchaseOrderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.warehouse_code
     *
     * @return the value of into_warehouse_order.warehouse_code
     *
     * @mbg.generated
     */
    public String getWarehouseCode() {
        return warehouseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.warehouse_code
     *
     * @param warehouseCode the value for into_warehouse_order.warehouse_code
     *
     * @mbg.generated
     */
    public void setWarehouseCode(String warehouseCode) {
        this.warehouseCode = warehouseCode == null ? null : warehouseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.system_order_num
     *
     * @return the value of into_warehouse_order.system_order_num
     *
     * @mbg.generated
     */
    public String getSystemOrderNum() {
        return systemOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.system_order_num
     *
     * @param systemOrderNum the value for into_warehouse_order.system_order_num
     *
     * @mbg.generated
     */
    public void setSystemOrderNum(String systemOrderNum) {
        this.systemOrderNum = systemOrderNum == null ? null : systemOrderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.order_type
     *
     * @return the value of into_warehouse_order.order_type
     *
     * @mbg.generated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.order_type
     *
     * @param orderType the value for into_warehouse_order.order_type
     *
     * @mbg.generated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.order_status
     *
     * @return the value of into_warehouse_order.order_status
     *
     * @mbg.generated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.order_status
     *
     * @param orderStatus the value for into_warehouse_order.order_status
     *
     * @mbg.generated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.logistics_code
     *
     * @return the value of into_warehouse_order.logistics_code
     *
     * @mbg.generated
     */
    public String getLogisticsCode() {
        return logisticsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.logistics_code
     *
     * @param logisticsCode the value for into_warehouse_order.logistics_code
     *
     * @mbg.generated
     */
    public void setLogisticsCode(String logisticsCode) {
        this.logisticsCode = logisticsCode == null ? null : logisticsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.logistics_name
     *
     * @return the value of into_warehouse_order.logistics_name
     *
     * @mbg.generated
     */
    public String getLogisticsName() {
        return logisticsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.logistics_name
     *
     * @param logisticsName the value for into_warehouse_order.logistics_name
     *
     * @mbg.generated
     */
    public void setLogisticsName(String logisticsName) {
        this.logisticsName = logisticsName == null ? null : logisticsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.express_code
     *
     * @return the value of into_warehouse_order.express_code
     *
     * @mbg.generated
     */
    public String getExpressCode() {
        return expressCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.express_code
     *
     * @param expressCode the value for into_warehouse_order.express_code
     *
     * @mbg.generated
     */
    public void setExpressCode(String expressCode) {
        this.expressCode = expressCode == null ? null : expressCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.send_company
     *
     * @return the value of into_warehouse_order.send_company
     *
     * @mbg.generated
     */
    public String getSendCompany() {
        return sendCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.send_company
     *
     * @param sendCompany the value for into_warehouse_order.send_company
     *
     * @mbg.generated
     */
    public void setSendCompany(String sendCompany) {
        this.sendCompany = sendCompany == null ? null : sendCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.send_name
     *
     * @return the value of into_warehouse_order.send_name
     *
     * @mbg.generated
     */
    public String getSendName() {
        return sendName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.send_name
     *
     * @param sendName the value for into_warehouse_order.send_name
     *
     * @mbg.generated
     */
    public void setSendName(String sendName) {
        this.sendName = sendName == null ? null : sendName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.send_tel
     *
     * @return the value of into_warehouse_order.send_tel
     *
     * @mbg.generated
     */
    public String getSendTel() {
        return sendTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.send_tel
     *
     * @param sendTel the value for into_warehouse_order.send_tel
     *
     * @mbg.generated
     */
    public void setSendTel(String sendTel) {
        this.sendTel = sendTel == null ? null : sendTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.send_mobile
     *
     * @return the value of into_warehouse_order.send_mobile
     *
     * @mbg.generated
     */
    public String getSendMobile() {
        return sendMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.send_mobile
     *
     * @param sendMobile the value for into_warehouse_order.send_mobile
     *
     * @mbg.generated
     */
    public void setSendMobile(String sendMobile) {
        this.sendMobile = sendMobile == null ? null : sendMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.send_email
     *
     * @return the value of into_warehouse_order.send_email
     *
     * @mbg.generated
     */
    public String getSendEmail() {
        return sendEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.send_email
     *
     * @param sendEmail the value for into_warehouse_order.send_email
     *
     * @mbg.generated
     */
    public void setSendEmail(String sendEmail) {
        this.sendEmail = sendEmail == null ? null : sendEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.send_province
     *
     * @return the value of into_warehouse_order.send_province
     *
     * @mbg.generated
     */
    public String getSendProvince() {
        return sendProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.send_province
     *
     * @param sendProvince the value for into_warehouse_order.send_province
     *
     * @mbg.generated
     */
    public void setSendProvince(String sendProvince) {
        this.sendProvince = sendProvince == null ? null : sendProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.send_city
     *
     * @return the value of into_warehouse_order.send_city
     *
     * @mbg.generated
     */
    public String getSendCity() {
        return sendCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.send_city
     *
     * @param sendCity the value for into_warehouse_order.send_city
     *
     * @mbg.generated
     */
    public void setSendCity(String sendCity) {
        this.sendCity = sendCity == null ? null : sendCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.send_area
     *
     * @return the value of into_warehouse_order.send_area
     *
     * @mbg.generated
     */
    public String getSendArea() {
        return sendArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.send_area
     *
     * @param sendArea the value for into_warehouse_order.send_area
     *
     * @mbg.generated
     */
    public void setSendArea(String sendArea) {
        this.sendArea = sendArea == null ? null : sendArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.send_detail_address
     *
     * @return the value of into_warehouse_order.send_detail_address
     *
     * @mbg.generated
     */
    public String getSendDetailAddress() {
        return sendDetailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.send_detail_address
     *
     * @param sendDetailAddress the value for into_warehouse_order.send_detail_address
     *
     * @mbg.generated
     */
    public void setSendDetailAddress(String sendDetailAddress) {
        this.sendDetailAddress = sendDetailAddress == null ? null : sendDetailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.receiver_company
     *
     * @return the value of into_warehouse_order.receiver_company
     *
     * @mbg.generated
     */
    public String getReceiverCompany() {
        return receiverCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.receiver_company
     *
     * @param receiverCompany the value for into_warehouse_order.receiver_company
     *
     * @mbg.generated
     */
    public void setReceiverCompany(String receiverCompany) {
        this.receiverCompany = receiverCompany == null ? null : receiverCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.receiver_name
     *
     * @return the value of into_warehouse_order.receiver_name
     *
     * @mbg.generated
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.receiver_name
     *
     * @param receiverName the value for into_warehouse_order.receiver_name
     *
     * @mbg.generated
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.receiver_tel
     *
     * @return the value of into_warehouse_order.receiver_tel
     *
     * @mbg.generated
     */
    public String getReceiverTel() {
        return receiverTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.receiver_tel
     *
     * @param receiverTel the value for into_warehouse_order.receiver_tel
     *
     * @mbg.generated
     */
    public void setReceiverTel(String receiverTel) {
        this.receiverTel = receiverTel == null ? null : receiverTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.receiver_mobile
     *
     * @return the value of into_warehouse_order.receiver_mobile
     *
     * @mbg.generated
     */
    public String getReceiverMobile() {
        return receiverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.receiver_mobile
     *
     * @param receiverMobile the value for into_warehouse_order.receiver_mobile
     *
     * @mbg.generated
     */
    public void setReceiverMobile(String receiverMobile) {
        this.receiverMobile = receiverMobile == null ? null : receiverMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.receiver_email
     *
     * @return the value of into_warehouse_order.receiver_email
     *
     * @mbg.generated
     */
    public String getReceiverEmail() {
        return receiverEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.receiver_email
     *
     * @param receiverEmail the value for into_warehouse_order.receiver_email
     *
     * @mbg.generated
     */
    public void setReceiverEmail(String receiverEmail) {
        this.receiverEmail = receiverEmail == null ? null : receiverEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.receiver_province
     *
     * @return the value of into_warehouse_order.receiver_province
     *
     * @mbg.generated
     */
    public String getReceiverProvince() {
        return receiverProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.receiver_province
     *
     * @param receiverProvince the value for into_warehouse_order.receiver_province
     *
     * @mbg.generated
     */
    public void setReceiverProvince(String receiverProvince) {
        this.receiverProvince = receiverProvince == null ? null : receiverProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.receiver_city
     *
     * @return the value of into_warehouse_order.receiver_city
     *
     * @mbg.generated
     */
    public String getReceiverCity() {
        return receiverCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.receiver_city
     *
     * @param receiverCity the value for into_warehouse_order.receiver_city
     *
     * @mbg.generated
     */
    public void setReceiverCity(String receiverCity) {
        this.receiverCity = receiverCity == null ? null : receiverCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.receiver_area
     *
     * @return the value of into_warehouse_order.receiver_area
     *
     * @mbg.generated
     */
    public String getReceiverArea() {
        return receiverArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.receiver_area
     *
     * @param receiverArea the value for into_warehouse_order.receiver_area
     *
     * @mbg.generated
     */
    public void setReceiverArea(String receiverArea) {
        this.receiverArea = receiverArea == null ? null : receiverArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.receiver_detail_address
     *
     * @return the value of into_warehouse_order.receiver_detail_address
     *
     * @mbg.generated
     */
    public String getReceiverDetailAddress() {
        return receiverDetailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.receiver_detail_address
     *
     * @param receiverDetailAddress the value for into_warehouse_order.receiver_detail_address
     *
     * @mbg.generated
     */
    public void setReceiverDetailAddress(String receiverDetailAddress) {
        this.receiverDetailAddress = receiverDetailAddress == null ? null : receiverDetailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.remark
     *
     * @return the value of into_warehouse_order.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.remark
     *
     * @param remark the value for into_warehouse_order.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.system_remark
     *
     * @return the value of into_warehouse_order.system_remark
     *
     * @mbg.generated
     */
    public String getSystemRemark() {
        return systemRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.system_remark
     *
     * @param systemRemark the value for into_warehouse_order.system_remark
     *
     * @mbg.generated
     */
    public void setSystemRemark(String systemRemark) {
        this.systemRemark = systemRemark == null ? null : systemRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.expect_start_time
     *
     * @return the value of into_warehouse_order.expect_start_time
     *
     * @mbg.generated
     */
    public Date getExpectStartTime() {
        return expectStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.expect_start_time
     *
     * @param expectStartTime the value for into_warehouse_order.expect_start_time
     *
     * @mbg.generated
     */
    public void setExpectStartTime(Date expectStartTime) {
        this.expectStartTime = expectStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.expect_end_time
     *
     * @return the value of into_warehouse_order.expect_end_time
     *
     * @mbg.generated
     */
    public Date getExpectEndTime() {
        return expectEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.expect_end_time
     *
     * @param expectEndTime the value for into_warehouse_order.expect_end_time
     *
     * @mbg.generated
     */
    public void setExpectEndTime(Date expectEndTime) {
        this.expectEndTime = expectEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.create_time
     *
     * @return the value of into_warehouse_order.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.create_time
     *
     * @param createTime the value for into_warehouse_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column into_warehouse_order.modify_time
     *
     * @return the value of into_warehouse_order.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column into_warehouse_order.modify_time
     *
     * @param modifyTime the value for into_warehouse_order.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}