package com.freesheep.biz.model;

import java.util.Date;

public class LogisticsInfoBO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_info.delivery_order_id
     *
     * @mbg.generated
     */
    private String deliveryOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_info.order_id
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_info.order_num
     *
     * @mbg.generated
     */
    private String orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_info.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_info.out_biz_code
     *
     * @mbg.generated
     */
    private String outBizCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_info.confirm_type
     *
     * @mbg.generated
     */
    private String confirmType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_info.order_confirm_time
     *
     * @mbg.generated
     */
    private String orderConfirmTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_info.logistics_code
     *
     * @mbg.generated
     */
    private String logisticsCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_info.logistics_name
     *
     * @mbg.generated
     */
    private String logisticsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_info.express_code
     *
     * @mbg.generated
     */
    private String expressCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_info.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_info.id
     *
     * @return the value of logistics_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_info.id
     *
     * @param id the value for logistics_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_info.delivery_order_id
     *
     * @return the value of logistics_info.delivery_order_id
     *
     * @mbg.generated
     */
    public String getDeliveryOrderId() {
        return deliveryOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_info.delivery_order_id
     *
     * @param deliveryOrderId the value for logistics_info.delivery_order_id
     *
     * @mbg.generated
     */
    public void setDeliveryOrderId(String deliveryOrderId) {
        this.deliveryOrderId = deliveryOrderId == null ? null : deliveryOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_info.order_id
     *
     * @return the value of logistics_info.order_id
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_info.order_id
     *
     * @param orderId the value for logistics_info.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_info.order_num
     *
     * @return the value of logistics_info.order_num
     *
     * @mbg.generated
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_info.order_num
     *
     * @param orderNum the value for logistics_info.order_num
     *
     * @mbg.generated
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_info.status
     *
     * @return the value of logistics_info.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_info.status
     *
     * @param status the value for logistics_info.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_info.out_biz_code
     *
     * @return the value of logistics_info.out_biz_code
     *
     * @mbg.generated
     */
    public String getOutBizCode() {
        return outBizCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_info.out_biz_code
     *
     * @param outBizCode the value for logistics_info.out_biz_code
     *
     * @mbg.generated
     */
    public void setOutBizCode(String outBizCode) {
        this.outBizCode = outBizCode == null ? null : outBizCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_info.confirm_type
     *
     * @return the value of logistics_info.confirm_type
     *
     * @mbg.generated
     */
    public String getConfirmType() {
        return confirmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_info.confirm_type
     *
     * @param confirmType the value for logistics_info.confirm_type
     *
     * @mbg.generated
     */
    public void setConfirmType(String confirmType) {
        this.confirmType = confirmType == null ? null : confirmType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_info.order_confirm_time
     *
     * @return the value of logistics_info.order_confirm_time
     *
     * @mbg.generated
     */
    public String getOrderConfirmTime() {
        return orderConfirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_info.order_confirm_time
     *
     * @param orderConfirmTime the value for logistics_info.order_confirm_time
     *
     * @mbg.generated
     */
    public void setOrderConfirmTime(String orderConfirmTime) {
        this.orderConfirmTime = orderConfirmTime == null ? null : orderConfirmTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_info.logistics_code
     *
     * @return the value of logistics_info.logistics_code
     *
     * @mbg.generated
     */
    public String getLogisticsCode() {
        return logisticsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_info.logistics_code
     *
     * @param logisticsCode the value for logistics_info.logistics_code
     *
     * @mbg.generated
     */
    public void setLogisticsCode(String logisticsCode) {
        this.logisticsCode = logisticsCode == null ? null : logisticsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_info.logistics_name
     *
     * @return the value of logistics_info.logistics_name
     *
     * @mbg.generated
     */
    public String getLogisticsName() {
        return logisticsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_info.logistics_name
     *
     * @param logisticsName the value for logistics_info.logistics_name
     *
     * @mbg.generated
     */
    public void setLogisticsName(String logisticsName) {
        this.logisticsName = logisticsName == null ? null : logisticsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_info.express_code
     *
     * @return the value of logistics_info.express_code
     *
     * @mbg.generated
     */
    public String getExpressCode() {
        return expressCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_info.express_code
     *
     * @param expressCode the value for logistics_info.express_code
     *
     * @mbg.generated
     */
    public void setExpressCode(String expressCode) {
        this.expressCode = expressCode == null ? null : expressCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_info.create_time
     *
     * @return the value of logistics_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_info.create_time
     *
     * @param createTime the value for logistics_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_info.modify_time
     *
     * @return the value of logistics_info.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_info.modify_time
     *
     * @param modifyTime the value for logistics_info.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}