package com.freesheep.biz.model;

import java.util.Date;

public class OrderCancelBO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cancel.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cancel.warehouse_code
     *
     * @mbg.generated
     */
    private String warehouseCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cancel.owner_code
     *
     * @mbg.generated
     */
    private String ownerCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cancel.order_code
     *
     * @mbg.generated
     */
    private String orderCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cancel.order_type
     *
     * @mbg.generated
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cancel.cancel_reason
     *
     * @mbg.generated
     */
    private String cancelReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cancel.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cancel.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cancel.id
     *
     * @return the value of order_cancel.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cancel.id
     *
     * @param id the value for order_cancel.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cancel.warehouse_code
     *
     * @return the value of order_cancel.warehouse_code
     *
     * @mbg.generated
     */
    public String getWarehouseCode() {
        return warehouseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cancel.warehouse_code
     *
     * @param warehouseCode the value for order_cancel.warehouse_code
     *
     * @mbg.generated
     */
    public void setWarehouseCode(String warehouseCode) {
        this.warehouseCode = warehouseCode == null ? null : warehouseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cancel.owner_code
     *
     * @return the value of order_cancel.owner_code
     *
     * @mbg.generated
     */
    public String getOwnerCode() {
        return ownerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cancel.owner_code
     *
     * @param ownerCode the value for order_cancel.owner_code
     *
     * @mbg.generated
     */
    public void setOwnerCode(String ownerCode) {
        this.ownerCode = ownerCode == null ? null : ownerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cancel.order_code
     *
     * @return the value of order_cancel.order_code
     *
     * @mbg.generated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cancel.order_code
     *
     * @param orderCode the value for order_cancel.order_code
     *
     * @mbg.generated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cancel.order_type
     *
     * @return the value of order_cancel.order_type
     *
     * @mbg.generated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cancel.order_type
     *
     * @param orderType the value for order_cancel.order_type
     *
     * @mbg.generated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cancel.cancel_reason
     *
     * @return the value of order_cancel.cancel_reason
     *
     * @mbg.generated
     */
    public String getCancelReason() {
        return cancelReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cancel.cancel_reason
     *
     * @param cancelReason the value for order_cancel.cancel_reason
     *
     * @mbg.generated
     */
    public void setCancelReason(String cancelReason) {
        this.cancelReason = cancelReason == null ? null : cancelReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cancel.create_time
     *
     * @return the value of order_cancel.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cancel.create_time
     *
     * @param createTime the value for order_cancel.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_cancel.modify_time
     *
     * @return the value of order_cancel.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_cancel.modify_time
     *
     * @param modifyTime the value for order_cancel.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}