package com.freesheep.biz.model;

import java.util.Date;

public class OutgoingOrderBO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.order_num
     *
     * @mbg.generated
     */
    private String orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.system_order_num
     *
     * @mbg.generated
     */
    private String systemOrderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.order_type
     *
     * @mbg.generated
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.order_status
     *
     * @mbg.generated
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.warehouse_code
     *
     * @mbg.generated
     */
    private String warehouseCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.schedule_date
     *
     * @mbg.generated
     */
    private String scheduleDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.logistics_code
     *
     * @mbg.generated
     */
    private String logisticsCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.logistics_name
     *
     * @mbg.generated
     */
    private String logisticsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.express_code
     *
     * @mbg.generated
     */
    private String expressCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.send_company
     *
     * @mbg.generated
     */
    private String sendCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.send_name
     *
     * @mbg.generated
     */
    private String sendName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.send_tel
     *
     * @mbg.generated
     */
    private String sendTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.send_mobile
     *
     * @mbg.generated
     */
    private String sendMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.send_id
     *
     * @mbg.generated
     */
    private String sendId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.send_car_no
     *
     * @mbg.generated
     */
    private String sendCarNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.receive_company
     *
     * @mbg.generated
     */
    private String receiveCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.receive_name
     *
     * @mbg.generated
     */
    private String receiveName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.receive_tel
     *
     * @mbg.generated
     */
    private String receiveTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.receive_mobile
     *
     * @mbg.generated
     */
    private String receiveMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.receive_email
     *
     * @mbg.generated
     */
    private String receiveEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.area
     *
     * @mbg.generated
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.detail_address
     *
     * @mbg.generated
     */
    private String detailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.receive_id
     *
     * @mbg.generated
     */
    private String receiveId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outgoing_order.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.id
     *
     * @return the value of outgoing_order.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.id
     *
     * @param id the value for outgoing_order.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.order_num
     *
     * @return the value of outgoing_order.order_num
     *
     * @mbg.generated
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.order_num
     *
     * @param orderNum the value for outgoing_order.order_num
     *
     * @mbg.generated
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.system_order_num
     *
     * @return the value of outgoing_order.system_order_num
     *
     * @mbg.generated
     */
    public String getSystemOrderNum() {
        return systemOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.system_order_num
     *
     * @param systemOrderNum the value for outgoing_order.system_order_num
     *
     * @mbg.generated
     */
    public void setSystemOrderNum(String systemOrderNum) {
        this.systemOrderNum = systemOrderNum == null ? null : systemOrderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.order_type
     *
     * @return the value of outgoing_order.order_type
     *
     * @mbg.generated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.order_type
     *
     * @param orderType the value for outgoing_order.order_type
     *
     * @mbg.generated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.order_status
     *
     * @return the value of outgoing_order.order_status
     *
     * @mbg.generated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.order_status
     *
     * @param orderStatus the value for outgoing_order.order_status
     *
     * @mbg.generated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.warehouse_code
     *
     * @return the value of outgoing_order.warehouse_code
     *
     * @mbg.generated
     */
    public String getWarehouseCode() {
        return warehouseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.warehouse_code
     *
     * @param warehouseCode the value for outgoing_order.warehouse_code
     *
     * @mbg.generated
     */
    public void setWarehouseCode(String warehouseCode) {
        this.warehouseCode = warehouseCode == null ? null : warehouseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.schedule_date
     *
     * @return the value of outgoing_order.schedule_date
     *
     * @mbg.generated
     */
    public String getScheduleDate() {
        return scheduleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.schedule_date
     *
     * @param scheduleDate the value for outgoing_order.schedule_date
     *
     * @mbg.generated
     */
    public void setScheduleDate(String scheduleDate) {
        this.scheduleDate = scheduleDate == null ? null : scheduleDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.logistics_code
     *
     * @return the value of outgoing_order.logistics_code
     *
     * @mbg.generated
     */
    public String getLogisticsCode() {
        return logisticsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.logistics_code
     *
     * @param logisticsCode the value for outgoing_order.logistics_code
     *
     * @mbg.generated
     */
    public void setLogisticsCode(String logisticsCode) {
        this.logisticsCode = logisticsCode == null ? null : logisticsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.logistics_name
     *
     * @return the value of outgoing_order.logistics_name
     *
     * @mbg.generated
     */
    public String getLogisticsName() {
        return logisticsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.logistics_name
     *
     * @param logisticsName the value for outgoing_order.logistics_name
     *
     * @mbg.generated
     */
    public void setLogisticsName(String logisticsName) {
        this.logisticsName = logisticsName == null ? null : logisticsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.express_code
     *
     * @return the value of outgoing_order.express_code
     *
     * @mbg.generated
     */
    public String getExpressCode() {
        return expressCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.express_code
     *
     * @param expressCode the value for outgoing_order.express_code
     *
     * @mbg.generated
     */
    public void setExpressCode(String expressCode) {
        this.expressCode = expressCode == null ? null : expressCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.send_company
     *
     * @return the value of outgoing_order.send_company
     *
     * @mbg.generated
     */
    public String getSendCompany() {
        return sendCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.send_company
     *
     * @param sendCompany the value for outgoing_order.send_company
     *
     * @mbg.generated
     */
    public void setSendCompany(String sendCompany) {
        this.sendCompany = sendCompany == null ? null : sendCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.send_name
     *
     * @return the value of outgoing_order.send_name
     *
     * @mbg.generated
     */
    public String getSendName() {
        return sendName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.send_name
     *
     * @param sendName the value for outgoing_order.send_name
     *
     * @mbg.generated
     */
    public void setSendName(String sendName) {
        this.sendName = sendName == null ? null : sendName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.send_tel
     *
     * @return the value of outgoing_order.send_tel
     *
     * @mbg.generated
     */
    public String getSendTel() {
        return sendTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.send_tel
     *
     * @param sendTel the value for outgoing_order.send_tel
     *
     * @mbg.generated
     */
    public void setSendTel(String sendTel) {
        this.sendTel = sendTel == null ? null : sendTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.send_mobile
     *
     * @return the value of outgoing_order.send_mobile
     *
     * @mbg.generated
     */
    public String getSendMobile() {
        return sendMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.send_mobile
     *
     * @param sendMobile the value for outgoing_order.send_mobile
     *
     * @mbg.generated
     */
    public void setSendMobile(String sendMobile) {
        this.sendMobile = sendMobile == null ? null : sendMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.send_id
     *
     * @return the value of outgoing_order.send_id
     *
     * @mbg.generated
     */
    public String getSendId() {
        return sendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.send_id
     *
     * @param sendId the value for outgoing_order.send_id
     *
     * @mbg.generated
     */
    public void setSendId(String sendId) {
        this.sendId = sendId == null ? null : sendId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.send_car_no
     *
     * @return the value of outgoing_order.send_car_no
     *
     * @mbg.generated
     */
    public String getSendCarNo() {
        return sendCarNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.send_car_no
     *
     * @param sendCarNo the value for outgoing_order.send_car_no
     *
     * @mbg.generated
     */
    public void setSendCarNo(String sendCarNo) {
        this.sendCarNo = sendCarNo == null ? null : sendCarNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.receive_company
     *
     * @return the value of outgoing_order.receive_company
     *
     * @mbg.generated
     */
    public String getReceiveCompany() {
        return receiveCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.receive_company
     *
     * @param receiveCompany the value for outgoing_order.receive_company
     *
     * @mbg.generated
     */
    public void setReceiveCompany(String receiveCompany) {
        this.receiveCompany = receiveCompany == null ? null : receiveCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.receive_name
     *
     * @return the value of outgoing_order.receive_name
     *
     * @mbg.generated
     */
    public String getReceiveName() {
        return receiveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.receive_name
     *
     * @param receiveName the value for outgoing_order.receive_name
     *
     * @mbg.generated
     */
    public void setReceiveName(String receiveName) {
        this.receiveName = receiveName == null ? null : receiveName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.receive_tel
     *
     * @return the value of outgoing_order.receive_tel
     *
     * @mbg.generated
     */
    public String getReceiveTel() {
        return receiveTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.receive_tel
     *
     * @param receiveTel the value for outgoing_order.receive_tel
     *
     * @mbg.generated
     */
    public void setReceiveTel(String receiveTel) {
        this.receiveTel = receiveTel == null ? null : receiveTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.receive_mobile
     *
     * @return the value of outgoing_order.receive_mobile
     *
     * @mbg.generated
     */
    public String getReceiveMobile() {
        return receiveMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.receive_mobile
     *
     * @param receiveMobile the value for outgoing_order.receive_mobile
     *
     * @mbg.generated
     */
    public void setReceiveMobile(String receiveMobile) {
        this.receiveMobile = receiveMobile == null ? null : receiveMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.receive_email
     *
     * @return the value of outgoing_order.receive_email
     *
     * @mbg.generated
     */
    public String getReceiveEmail() {
        return receiveEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.receive_email
     *
     * @param receiveEmail the value for outgoing_order.receive_email
     *
     * @mbg.generated
     */
    public void setReceiveEmail(String receiveEmail) {
        this.receiveEmail = receiveEmail == null ? null : receiveEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.province
     *
     * @return the value of outgoing_order.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.province
     *
     * @param province the value for outgoing_order.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.city
     *
     * @return the value of outgoing_order.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.city
     *
     * @param city the value for outgoing_order.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.area
     *
     * @return the value of outgoing_order.area
     *
     * @mbg.generated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.area
     *
     * @param area the value for outgoing_order.area
     *
     * @mbg.generated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.detail_address
     *
     * @return the value of outgoing_order.detail_address
     *
     * @mbg.generated
     */
    public String getDetailAddress() {
        return detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.detail_address
     *
     * @param detailAddress the value for outgoing_order.detail_address
     *
     * @mbg.generated
     */
    public void setDetailAddress(String detailAddress) {
        this.detailAddress = detailAddress == null ? null : detailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.receive_id
     *
     * @return the value of outgoing_order.receive_id
     *
     * @mbg.generated
     */
    public String getReceiveId() {
        return receiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.receive_id
     *
     * @param receiveId the value for outgoing_order.receive_id
     *
     * @mbg.generated
     */
    public void setReceiveId(String receiveId) {
        this.receiveId = receiveId == null ? null : receiveId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.remark
     *
     * @return the value of outgoing_order.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.remark
     *
     * @param remark the value for outgoing_order.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.create_time
     *
     * @return the value of outgoing_order.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.create_time
     *
     * @param createTime the value for outgoing_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outgoing_order.modify_time
     *
     * @return the value of outgoing_order.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outgoing_order.modify_time
     *
     * @param modifyTime the value for outgoing_order.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}