package com.freesheep.biz.model;

import java.util.Date;

public class ReturnOrderBO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.order_num
     *
     * @mbg.generated
     */
    private String orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.pre_delivery_order_num
     *
     * @mbg.generated
     */
    private String preDeliveryOrderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.order_type
     *
     * @mbg.generated
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.logistics_code
     *
     * @mbg.generated
     */
    private String logisticsCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.express_code
     *
     * @mbg.generated
     */
    private String expressCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.return_reason
     *
     * @mbg.generated
     */
    private String returnReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.buyer_nick
     *
     * @mbg.generated
     */
    private String buyerNick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.company
     *
     * @mbg.generated
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.area
     *
     * @mbg.generated
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.detailAddress
     *
     * @mbg.generated
     */
    private String detailaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.system_order_id
     *
     * @mbg.generated
     */
    private String systemOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.id
     *
     * @return the value of return_order.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.id
     *
     * @param id the value for return_order.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.order_num
     *
     * @return the value of return_order.order_num
     *
     * @mbg.generated
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.order_num
     *
     * @param orderNum the value for return_order.order_num
     *
     * @mbg.generated
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.pre_delivery_order_num
     *
     * @return the value of return_order.pre_delivery_order_num
     *
     * @mbg.generated
     */
    public String getPreDeliveryOrderNum() {
        return preDeliveryOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.pre_delivery_order_num
     *
     * @param preDeliveryOrderNum the value for return_order.pre_delivery_order_num
     *
     * @mbg.generated
     */
    public void setPreDeliveryOrderNum(String preDeliveryOrderNum) {
        this.preDeliveryOrderNum = preDeliveryOrderNum == null ? null : preDeliveryOrderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.order_type
     *
     * @return the value of return_order.order_type
     *
     * @mbg.generated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.order_type
     *
     * @param orderType the value for return_order.order_type
     *
     * @mbg.generated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.logistics_code
     *
     * @return the value of return_order.logistics_code
     *
     * @mbg.generated
     */
    public String getLogisticsCode() {
        return logisticsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.logistics_code
     *
     * @param logisticsCode the value for return_order.logistics_code
     *
     * @mbg.generated
     */
    public void setLogisticsCode(String logisticsCode) {
        this.logisticsCode = logisticsCode == null ? null : logisticsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.express_code
     *
     * @return the value of return_order.express_code
     *
     * @mbg.generated
     */
    public String getExpressCode() {
        return expressCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.express_code
     *
     * @param expressCode the value for return_order.express_code
     *
     * @mbg.generated
     */
    public void setExpressCode(String expressCode) {
        this.expressCode = expressCode == null ? null : expressCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.return_reason
     *
     * @return the value of return_order.return_reason
     *
     * @mbg.generated
     */
    public String getReturnReason() {
        return returnReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.return_reason
     *
     * @param returnReason the value for return_order.return_reason
     *
     * @mbg.generated
     */
    public void setReturnReason(String returnReason) {
        this.returnReason = returnReason == null ? null : returnReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.buyer_nick
     *
     * @return the value of return_order.buyer_nick
     *
     * @mbg.generated
     */
    public String getBuyerNick() {
        return buyerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.buyer_nick
     *
     * @param buyerNick the value for return_order.buyer_nick
     *
     * @mbg.generated
     */
    public void setBuyerNick(String buyerNick) {
        this.buyerNick = buyerNick == null ? null : buyerNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.company
     *
     * @return the value of return_order.company
     *
     * @mbg.generated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.company
     *
     * @param company the value for return_order.company
     *
     * @mbg.generated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.name
     *
     * @return the value of return_order.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.name
     *
     * @param name the value for return_order.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.tel
     *
     * @return the value of return_order.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.tel
     *
     * @param tel the value for return_order.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.mobile
     *
     * @return the value of return_order.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.mobile
     *
     * @param mobile the value for return_order.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.email
     *
     * @return the value of return_order.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.email
     *
     * @param email the value for return_order.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.province
     *
     * @return the value of return_order.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.province
     *
     * @param province the value for return_order.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.city
     *
     * @return the value of return_order.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.city
     *
     * @param city the value for return_order.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.area
     *
     * @return the value of return_order.area
     *
     * @mbg.generated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.area
     *
     * @param area the value for return_order.area
     *
     * @mbg.generated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.detailAddress
     *
     * @return the value of return_order.detailAddress
     *
     * @mbg.generated
     */
    public String getDetailaddress() {
        return detailaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.detailAddress
     *
     * @param detailaddress the value for return_order.detailAddress
     *
     * @mbg.generated
     */
    public void setDetailaddress(String detailaddress) {
        this.detailaddress = detailaddress == null ? null : detailaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.remark
     *
     * @return the value of return_order.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.remark
     *
     * @param remark the value for return_order.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.system_order_id
     *
     * @return the value of return_order.system_order_id
     *
     * @mbg.generated
     */
    public String getSystemOrderId() {
        return systemOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.system_order_id
     *
     * @param systemOrderId the value for return_order.system_order_id
     *
     * @mbg.generated
     */
    public void setSystemOrderId(String systemOrderId) {
        this.systemOrderId = systemOrderId == null ? null : systemOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.create_time
     *
     * @return the value of return_order.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.create_time
     *
     * @param createTime the value for return_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.modify_time
     *
     * @return the value of return_order.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.modify_time
     *
     * @param modifyTime the value for return_order.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}