package com.freesheep.biz.model;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.List;

public class ShowInfoBO {

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private List<StMomentsBO> momentsList;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private List<StProductsBO> productsList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column show_info.id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column show_info.show_id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String showId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column show_info.info_type
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer infoType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column show_info.create_time
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column show_info.modify_time
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column show_info.remark
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column show_info.id
     *
     * @return the value of show_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column show_info.id
     *
     * @param id the value for show_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column show_info.show_id
     *
     * @return the value of show_info.show_id
     *
     * @mbg.generated
     */
    public String getShowId() {
        return showId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column show_info.show_id
     *
     * @param showId the value for show_info.show_id
     *
     * @mbg.generated
     */
    public void setShowId(String showId) {
        this.showId = showId == null ? null : showId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column show_info.info_type
     *
     * @return the value of show_info.info_type
     *
     * @mbg.generated
     */
    public Integer getInfoType() {
        return infoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column show_info.info_type
     *
     * @param infoType the value for show_info.info_type
     *
     * @mbg.generated
     */
    public void setInfoType(Integer infoType) {
        this.infoType = infoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column show_info.create_time
     *
     * @return the value of show_info.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column show_info.create_time
     *
     * @param createTime the value for show_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column show_info.modify_time
     *
     * @return the value of show_info.modify_time
     *
     * @mbg.generated
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column show_info.modify_time
     *
     * @param modifyTime the value for show_info.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime == null ? null : modifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column show_info.remark
     *
     * @return the value of show_info.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column show_info.remark
     *
     * @param remark the value for show_info.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public List<StMomentsBO> getMomentsList() {
        return momentsList;
    }

    public void setMomentsList(List<StMomentsBO> momentsList) {
        this.momentsList = momentsList;
    }

    public List<StProductsBO> getProductsList() {
        return productsList;
    }

    public void setProductsList(List<StProductsBO> productsList) {
        this.productsList = productsList;
    }
}