package com.freesheep.biz.model;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.Date;

public class StClaimOrderBO {

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String sheepImg;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String sheepNickname;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private long sheepBreedsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_claim_order.id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_claim_order.user_id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_claim_order.order_num
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_claim_order.price
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String price;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_claim_order.price
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String serialNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_claim_order.pay_status
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_claim_order.pay_type
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_claim_order.pay_price
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String payPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_claim_order.order_status
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_claim_order.sheep_id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Long sheepId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_claim_order.name
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_claim_order.phone
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_claim_order.create_time
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_claim_order.modify_time
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_claim_order.modify_time
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_claim_order.id
     *
     * @return the value of st_claim_order.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_claim_order.id
     *
     * @param id the value for st_claim_order.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_claim_order.user_id
     *
     * @return the value of st_claim_order.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_claim_order.user_id
     *
     * @param userId the value for st_claim_order.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_claim_order.order_num
     *
     * @return the value of st_claim_order.order_num
     *
     * @mbg.generated
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_claim_order.address
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_claim_order.remark
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String remark;


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_claim_order.order_num
     *
     * @param orderNum the value for st_claim_order.order_num
     *
     * @mbg.generated
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_claim_order.price
     *
     * @return the value of st_claim_order.price
     *
     * @mbg.generated
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_claim_order.price
     *
     * @param price the value for st_claim_order.price
     *
     * @mbg.generated
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_claim_order.pay_status
     *
     * @return the value of st_claim_order.pay_status
     *
     * @mbg.generated
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_claim_order.pay_status
     *
     * @param payStatus the value for st_claim_order.pay_status
     *
     * @mbg.generated
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_claim_order.pay_type
     *
     * @return the value of st_claim_order.pay_type
     *
     * @mbg.generated
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_claim_order.pay_type
     *
     * @param payType the value for st_claim_order.pay_type
     *
     * @mbg.generated
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_claim_order.pay_price
     *
     * @return the value of st_claim_order.pay_price
     *
     * @mbg.generated
     */
    public String getPayPrice() {
        return payPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_claim_order.pay_price
     *
     * @param payPrice the value for st_claim_order.pay_price
     *
     * @mbg.generated
     */
    public void setPayPrice(String payPrice) {
        this.payPrice = payPrice == null ? null : payPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_claim_order.order_status
     *
     * @return the value of st_claim_order.order_status
     *
     * @mbg.generated
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_claim_order.order_status
     *
     * @param orderStatus the value for st_claim_order.order_status
     *
     * @mbg.generated
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_claim_order.sheep_id
     *
     * @return the value of st_claim_order.sheep_id
     *
     * @mbg.generated
     */
    public Long getSheepId() {
        return sheepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_claim_order.sheep_id
     *
     * @param sheepId the value for st_claim_order.sheep_id
     *
     * @mbg.generated
     */
    public void setSheepId(Long sheepId) {
        this.sheepId = sheepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_claim_order.name
     *
     * @return the value of st_claim_order.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_claim_order.name
     *
     * @param name the value for st_claim_order.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_claim_order.phone
     *
     * @return the value of st_claim_order.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_claim_order.phone
     *
     * @param phone the value for st_claim_order.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_claim_order.create_time
     *
     * @return the value of st_claim_order.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_claim_order.create_time
     *
     * @param createTime the value for st_claim_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_claim_order.modify_time
     *
     * @return the value of st_claim_order.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_claim_order.modify_time
     *
     * @param modifyTime the value for st_claim_order.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_claim_order.address
     *
     * @return the value of st_claim_order.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_claim_order.address
     *
     * @param address the value for st_claim_order.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_claim_order.remark
     *
     * @return the value of st_claim_order.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_claim_order.remark
     *
     * @param remark the value for st_claim_order.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public String getSerialNumber() {
        return serialNumber;
    }

    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    public Date getPayTime() {
        return payTime;
    }

    public String getSheepImg() {
        return sheepImg;
    }

    public void setSheepImg(String sheepImg) {
        this.sheepImg = sheepImg;
    }

    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    public String getSheepNickname() {
        return sheepNickname;
    }

    public void setSheepNickname(String sheepNickname) {
        this.sheepNickname = sheepNickname;
    }

    public long getSheepBreedsId() {
        return sheepBreedsId;
    }

    public void setSheepBreedsId(long sheepBreedsId) {
        this.sheepBreedsId = sheepBreedsId;
    }


    @Override
    public String toString() {
        return "StClaimOrderBO{" +
                "sheepImg='" + sheepImg + '\'' +
                ", sheepNickname='" + sheepNickname + '\'' +
                ", sheepBreedsId=" + sheepBreedsId +
                ", id=" + id +
                ", userId=" + userId +
                ", orderNum='" + orderNum + '\'' +
                ", price='" + price + '\'' +
                ", serialNumber='" + serialNumber + '\'' +
                ", payStatus=" + payStatus +
                ", payType=" + payType +
                ", payPrice='" + payPrice + '\'' +
                ", orderStatus=" + orderStatus +
                ", sheepId=" + sheepId +
                ", name='" + name + '\'' +
                ", phone='" + phone + '\'' +
                ", createTime=" + createTime +
                ", payTime=" + payTime +
                ", modifyTime=" + modifyTime +
                ", address='" + address + '\'' +
                ", remark='" + remark + '\'' +
                '}';
    }
}