package com.freesheep.biz.model;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.Date;

public class StDeviceBO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_device.id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_device.device_num
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String deviceNum;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_device.device_num
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String phone;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_device.device_num
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String ipAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_device.device_type_id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer deviceTypeId;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_device.device_power
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer devicePower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_device.device_status_id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Long deviceStatusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_device.create_time
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_device.modify_time
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_device.id
     *
     * @return the value of st_device.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_device.id
     *
     * @param id the value for st_device.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_device.device_num
     *
     * @return the value of st_device.device_num
     *
     * @mbg.generated
     */
    public String getDeviceNum() {
        return deviceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_device.device_num
     *
     * @param deviceNum the value for st_device.device_num
     *
     * @mbg.generated
     */
    public void setDeviceNum(String deviceNum) {
        this.deviceNum = deviceNum == null ? null : deviceNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_device.device_type_id
     *
     * @return the value of st_device.device_type_id
     *
     * @mbg.generated
     */
    public Integer getDeviceTypeId() {
        return deviceTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_device.device_type_id
     *
     * @param deviceTypeId the value for st_device.device_type_id
     *
     * @mbg.generated
     */
    public void setDeviceTypeId(Integer deviceTypeId) {
        this.deviceTypeId = deviceTypeId;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_device.device_power
     *
     * @return the value of st_device.device_power
     *
     * @mbg.generated
     */
    public Integer getDevicePower() {
        return devicePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_device.device_power
     *
     * @param devicePower the value for st_device.device_power
     *
     * @mbg.generated
     */
    public void setDevicePower(Integer devicePower) {
        this.devicePower = devicePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_device.device_status_id
     *
     * @return the value of st_device.device_status_id
     *
     * @mbg.generated
     */
    public Long getDeviceStatusId() {
        return deviceStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_device.device_status_id
     *
     * @param deviceStatusId the value for st_device.device_status_id
     *
     * @mbg.generated
     */
    public void setDeviceStatusId(Long deviceStatusId) {
        this.deviceStatusId = deviceStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_device.create_time
     *
     * @return the value of st_device.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_device.create_time
     *
     * @param createTime the value for st_device.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_device.modify_time
     *
     * @return the value of st_device.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_device.modify_time
     *
     * @param modifyTime the value for st_device.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getIpAddress() {
        return ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }
}