package com.freesheep.biz.model;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.Date;

public class StMomentsDissBO {

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private StUsersBO usersInfo;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private StUsersBO toUsersInfo;


    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String toUserNickname;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String toUserAvator;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer toUserGender;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String fromUserNickname;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String fromUserAvator;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer fromUserGender;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_moments_diss.id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_moments_diss.mid
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_moments_diss.fid
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_moments_diss.user_id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_moments_diss.created
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_moments_diss.modified
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Date modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_moments_diss.content
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_moments_diss.id
     *
     * @return the value of st_moments_diss.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_moments_diss.id
     *
     * @param id the value for st_moments_diss.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_moments_diss.mid
     *
     * @return the value of st_moments_diss.mid
     *
     * @mbg.generated
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_moments_diss.mid
     *
     * @param mid the value for st_moments_diss.mid
     *
     * @mbg.generated
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_moments_diss.fid
     *
     * @return the value of st_moments_diss.fid
     *
     * @mbg.generated
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_moments_diss.fid
     *
     * @param fid the value for st_moments_diss.fid
     *
     * @mbg.generated
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_moments_diss.user_id
     *
     * @return the value of st_moments_diss.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_moments_diss.user_id
     *
     * @param userId the value for st_moments_diss.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_moments_diss.created
     *
     * @return the value of st_moments_diss.created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_moments_diss.created
     *
     * @param created the value for st_moments_diss.created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_moments_diss.modified
     *
     * @return the value of st_moments_diss.modified
     *
     * @mbg.generated
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_moments_diss.modified
     *
     * @param modified the value for st_moments_diss.modified
     *
     * @mbg.generated
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_moments_diss.content
     *
     * @return the value of st_moments_diss.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_moments_diss.content
     *
     * @param content the value for st_moments_diss.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    public StUsersBO getUsersInfo() {
        return usersInfo;
    }

    public void setUsersInfo(StUsersBO usersInfo) {
        this.usersInfo = usersInfo;
    }

    public StUsersBO getToUsersInfo() {
        return toUsersInfo;
    }

    public void setToUsersInfo(StUsersBO toUsersInfo) {
        this.toUsersInfo = toUsersInfo;
    }

    public String getToUserNickname() {
        return toUserNickname;
    }

    public void setToUserNickname(String toUserNickname) {
        this.toUserNickname = toUserNickname;
    }

    public String getToUserAvator() {
        return toUserAvator;
    }

    public void setToUserAvator(String toUserAvator) {
        this.toUserAvator = toUserAvator;
    }

    public Integer getToUserGender() {
        return toUserGender;
    }

    public void setToUserGender(Integer toUserGender) {
        this.toUserGender = toUserGender;
    }

    public String getFromUserNickname() {
        return fromUserNickname;
    }

    public void setFromUserNickname(String fromUserNickname) {
        this.fromUserNickname = fromUserNickname;
    }

    public String getFromUserAvator() {
        return fromUserAvator;
    }

    public void setFromUserAvator(String fromUserAvator) {
        this.fromUserAvator = fromUserAvator;
    }

    public Integer getFromUserGender() {
        return fromUserGender;
    }

    public void setFromUserGender(Integer fromUserGender) {
        this.fromUserGender = fromUserGender;
    }

    @Override
    public String toString() {
        return "StMomentsDissBO{" +
                "usersInfo=" + usersInfo +
                ", toUsersInfo=" + toUsersInfo +
                ", toUserNickname='" + toUserNickname + '\'' +
                ", toUserAvator='" + toUserAvator + '\'' +
                ", toUserGender=" + toUserGender +
                ", fromUserNickname='" + fromUserNickname + '\'' +
                ", fromUserAvator='" + fromUserAvator + '\'' +
                ", fromUserGender=" + fromUserGender +
                ", id=" + id +
                ", mid=" + mid +
                ", fid=" + fid +
                ", userId=" + userId +
                ", created=" + created +
                ", modified=" + modified +
                ", content='" + content + '\'' +
                '}';
    }
}