package com.freesheep.biz.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.Date;
import java.util.List;

public class StMomentsBO {

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private List<StMomentsDissBO> momentList;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private List<StMomentsDigsBO> digs;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private List<StMomentsMediaBO> media;


    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String avator;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String nickname;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer gender;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_moments.id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_moments.user_id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_moments.dig
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer dig;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_moments.dis
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer dis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_moments.share_count
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Long shareCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_moments.mtype
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer mtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_moments.created
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_moments.modified
     *
     * @mbg.generated
     */
    @JsonIgnore
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Date modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_moments.content
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_moments.content
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_moments.id
     *
     * @return the value of st_moments.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_moments.id
     *
     * @param id the value for st_moments.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_moments.user_id
     *
     * @return the value of st_moments.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_moments.user_id
     *
     * @param userId the value for st_moments.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_moments.dig
     *
     * @return the value of st_moments.dig
     *
     * @mbg.generated
     */
    public Integer getDig() {
        return dig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_moments.dig
     *
     * @param dig the value for st_moments.dig
     *
     * @mbg.generated
     */
    public void setDig(Integer dig) {
        this.dig = dig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_moments.dis
     *
     * @return the value of st_moments.dis
     *
     * @mbg.generated
     */
    public Integer getDis() {
        return dis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_moments.dis
     *
     * @param dis the value for st_moments.dis
     *
     * @mbg.generated
     */
    public void setDis(Integer dis) {
        this.dis = dis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_moments.share_count
     *
     * @return the value of st_moments.share_count
     *
     * @mbg.generated
     */
    public Long getShareCount() {
        return shareCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_moments.share_count
     *
     * @param shareCount the value for st_moments.share_count
     *
     * @mbg.generated
     */
    public void setShareCount(Long shareCount) {
        this.shareCount = shareCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_moments.mtype
     *
     * @return the value of st_moments.mtype
     *
     * @mbg.generated
     */
    public Integer getMtype() {
        return mtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_moments.mtype
     *
     * @param mtype the value for st_moments.mtype
     *
     * @mbg.generated
     */
    public void setMtype(Integer mtype) {
        this.mtype = mtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_moments.created
     *
     * @return the value of st_moments.created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_moments.created
     *
     * @param created the value for st_moments.created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_moments.modified
     *
     * @return the value of st_moments.modified
     *
     * @mbg.generated
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_moments.modified
     *
     * @param modified the value for st_moments.modified
     *
     * @mbg.generated
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_moments.content
     *
     * @return the value of st_moments.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_moments.content
     *
     * @param content the value for st_moments.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    public String getAvator() {
        return avator;
    }

    public void setAvator(String avator) {
        this.avator = avator;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public Integer getGender() {
        return gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public List<StMomentsDissBO> getMomentList() {
        return momentList;
    }

    public void setMomentList(List<StMomentsDissBO> momentList) {
        this.momentList = momentList;
    }

    public List<StMomentsDigsBO> getDigs() {
        return digs;
    }

    public void setDigs(List<StMomentsDigsBO> digs) {
        this.digs = digs;
    }

    public List<StMomentsMediaBO> getMedia() {
        return media;
    }

    public void setMedia(List<StMomentsMediaBO> media) {
        this.media = media;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }


    @Override
    public String toString() {
        return "StMomentsBO{" +
                "momentList=" + momentList +
                ", digs=" + digs +
                ", media=" + media +
                ", avator='" + avator + '\'' +
                ", nickname='" + nickname + '\'' +
                ", gender=" + gender +
                ", id=" + id +
                ", userId=" + userId +
                ", dig=" + dig +
                ", dis=" + dis +
                ", shareCount=" + shareCount +
                ", mtype=" + mtype +
                ", created=" + created +
                ", modified=" + modified +
                ", content='" + content + '\'' +
                ", location='" + location + '\'' +
                '}';
    }
}