package com.freesheep.biz.model;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.Date;

public class StPastureBO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_pasture.id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_pasture.name
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_pasture.longitude
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_pasture.latitude
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_pasture.latitude
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_pasture.sheep_breeds_id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String sheepBreedsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_pasture.create_time
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_pasture.modify_time
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_pasture.pasture_location
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String pastureLocation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_pasture.id
     *
     * @return the value of st_pasture.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_pasture.id
     *
     * @param id the value for st_pasture.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_pasture.name
     *
     * @return the value of st_pasture.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_pasture.name
     *
     * @param name the value for st_pasture.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_pasture.longitude
     *
     * @return the value of st_pasture.longitude
     *
     * @mbg.generated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_pasture.longitude
     *
     * @param longitude the value for st_pasture.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_pasture.latitude
     *
     * @return the value of st_pasture.latitude
     *
     * @mbg.generated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_pasture.latitude
     *
     * @param latitude the value for st_pasture.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_pasture.sheep_breeds_id
     *
     * @return the value of st_pasture.sheep_breeds_id
     *
     * @mbg.generated
     */
    public String getSheepBreedsId() {
        return sheepBreedsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_pasture.sheep_breeds_id
     *
     * @param sheepBreedsId the value for st_pasture.sheep_breeds_id
     *
     * @mbg.generated
     */
    public void setSheepBreedsId(String sheepBreedsId) {
        this.sheepBreedsId = sheepBreedsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_pasture.create_time
     *
     * @return the value of st_pasture.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_pasture.create_time
     *
     * @param createTime the value for st_pasture.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_pasture.modify_time
     *
     * @return the value of st_pasture.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_pasture.modify_time
     *
     * @param modifyTime the value for st_pasture.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_pasture.pasture_location
     *
     * @return the value of st_pasture.pasture_location
     *
     * @mbg.generated
     */
    public String getPastureLocation() {
        return pastureLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_pasture.pasture_location
     *
     * @param pastureLocation the value for st_pasture.pasture_location
     *
     * @mbg.generated
     */
    public void setPastureLocation(String pastureLocation) {
        this.pastureLocation = pastureLocation == null ? null : pastureLocation.trim();
    }

    public String getImg() {
        return img;
    }

    public void setImg(String img) {
        this.img = img;
    }

}