package com.freesheep.biz.model;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.Date;

public class StProductsImagesBO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_products_images.id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_products_images.pr_id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer prId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_products_images.image
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_products_images.created
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_products_images.modified
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Date modified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_products_images.id
     *
     * @return the value of st_products_images.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_products_images.id
     *
     * @param id the value for st_products_images.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_products_images.pr_id
     *
     * @return the value of st_products_images.pr_id
     *
     * @mbg.generated
     */
    public Integer getPrId() {
        return prId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_products_images.pr_id
     *
     * @param prId the value for st_products_images.pr_id
     *
     * @mbg.generated
     */
    public void setPrId(Integer prId) {
        this.prId = prId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_products_images.image
     *
     * @return the value of st_products_images.image
     *
     * @mbg.generated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_products_images.image
     *
     * @param image the value for st_products_images.image
     *
     * @mbg.generated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_products_images.created
     *
     * @return the value of st_products_images.created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_products_images.created
     *
     * @param created the value for st_products_images.created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_products_images.modified
     *
     * @return the value of st_products_images.modified
     *
     * @mbg.generated
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_products_images.modified
     *
     * @param modified the value for st_products_images.modified
     *
     * @mbg.generated
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }


    @Override
    public String toString() {
        return "StProductsImagesBO{" +
                "id=" + id +
                ", prId=" + prId +
                ", image='" + image + '\'' +
                ", created=" + created +
                ", modified=" + modified +
                '}';
    }
}