package com.freesheep.biz.model;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.Date;
import java.util.List;

public class StProductsBO {
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer payNumber;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String image;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String logisticsGoodsCode;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Long productId;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String productCode;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String productQrCode;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer isShow;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private List<StProductInfoBO> infoList;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private List<StProductsImagesBO> imgList;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_products.id
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_products.products
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String products;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_products.price
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_products.sale
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Float sale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_products.unit
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_products.origin
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String origin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_products.count
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_products.number
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_products.created
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_products.modified
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Date modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_products.intro
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String intro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_products.id
     *
     * @return the value of st_products.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_products.id
     *
     * @param id the value for st_products.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_products.products
     *
     * @return the value of st_products.products
     *
     * @mbg.generated
     */
    public String getProducts() {
        return products;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_products.products
     *
     * @param products the value for st_products.products
     *
     * @mbg.generated
     */
    public void setProducts(String products) {
        this.products = products == null ? null : products.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_products.price
     *
     * @return the value of st_products.price
     *
     * @mbg.generated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_products.price
     *
     * @param price the value for st_products.price
     *
     * @mbg.generated
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_products.sale
     *
     * @return the value of st_products.sale
     *
     * @mbg.generated
     */
    public Float getSale() {
        return sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_products.sale
     *
     * @param sale the value for st_products.sale
     *
     * @mbg.generated
     */
    public void setSale(Float sale) {
        this.sale = sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_products.unit
     *
     * @return the value of st_products.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_products.unit
     *
     * @param unit the value for st_products.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_products.origin
     *
     * @return the value of st_products.origin
     *
     * @mbg.generated
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_products.origin
     *
     * @param origin the value for st_products.origin
     *
     * @mbg.generated
     */
    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_products.count
     *
     * @return the value of st_products.count
     *
     * @mbg.generated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_products.count
     *
     * @param count the value for st_products.count
     *
     * @mbg.generated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_products.number
     *
     * @return the value of st_products.number
     *
     * @mbg.generated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_products.number
     *
     * @param number the value for st_products.number
     *
     * @mbg.generated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_products.created
     *
     * @return the value of st_products.created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_products.created
     *
     * @param created the value for st_products.created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_products.modified
     *
     * @return the value of st_products.modified
     *
     * @mbg.generated
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_products.modified
     *
     * @param modified the value for st_products.modified
     *
     * @mbg.generated
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_products.intro
     *
     * @return the value of st_products.intro
     *
     * @mbg.generated
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_products.intro
     *
     * @param intro the value for st_products.intro
     *
     * @mbg.generated
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public Integer getPayNumber() {
        return payNumber;
    }

    public void setPayNumber(Integer payNumber) {
        this.payNumber = payNumber;
    }

    public String getLogisticsGoodsCode() {
        return logisticsGoodsCode;
    }

    public void setLogisticsGoodsCode(String logisticsGoodsCode) {
        this.logisticsGoodsCode = logisticsGoodsCode;
    }

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public String getProductCode() {
        return productCode;
    }

    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    public String getProductQrCode() {
        return productQrCode;
    }

    public void setProductQrCode(String productQrCode) {
        this.productQrCode = productQrCode;
    }

    public Integer getIsShow() {
        return isShow;
    }

    public void setIsShow(Integer isShow) {
        this.isShow = isShow;
    }

    public List<StProductInfoBO> getInfoList() {
        return infoList;
    }

    public void setInfoList(List<StProductInfoBO> infoList) {
        this.infoList = infoList;
    }

    public List<StProductsImagesBO> getImgList() {
        return imgList;
    }

    public void setImgList(List<StProductsImagesBO> imgList) {
        this.imgList = imgList;
    }

    @Override
    public String toString() {
        return "StProductsBO{" +
                "payNumber=" + payNumber +
                ", image='" + image + '\'' +
                ", logisticsGoodsCode='" + logisticsGoodsCode + '\'' +
                ", productId=" + productId +
                ", productCode='" + productCode + '\'' +
                ", productQrCode='" + productQrCode + '\'' +
                ", isShow=" + isShow +
                ", id=" + id +
                ", products='" + products + '\'' +
                ", price=" + price +
                ", sale=" + sale +
                ", unit='" + unit + '\'' +
                ", origin='" + origin + '\'' +
                ", count=" + count +
                ", number=" + number +
                ", created=" + created +
                ", modified=" + modified +
                ", intro='" + intro + '\'' +
                '}';
    }
}